//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCareApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarCareApplication.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string AD_X0001 {
            get {
                return ResourceManager.GetString("AD-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string AD_X0002 {
            get {
                return ResourceManager.GetString("AD-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating an Address with empty values, please check your inputs..
        /// </summary>
        internal static string AD_X0003 {
            get {
                return ResourceManager.GetString("AD-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Key is not provided.
        /// </summary>
        internal static string AD_X0004 {
            get {
                return ResourceManager.GetString("AD-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can&apos;t be empty.
        /// </summary>
        internal static string AD_X0005 {
            get {
                return ResourceManager.GetString("AD-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        internal static string AD_X0006 {
            get {
                return ResourceManager.GetString("AD-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full address can&apos;t be empty.
        /// </summary>
        internal static string AD_X0007 {
            get {
                return ResourceManager.GetString("AD-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers can not be calculated, please check your live location is turned on.
        /// </summary>
        internal static string AD_X0008 {
            get {
                return ResourceManager.GetString("AD-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t detect your current location, please check your live location is turned on.
        /// </summary>
        internal static string AD_X0009 {
            get {
                return ResourceManager.GetString("AD-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is not found.
        /// </summary>
        internal static string AD_X0010 {
            get {
                return ResourceManager.GetString("AD-X0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        internal static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App Provides Car Washing Service by 4 CarCareApplication company.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarCareApplication is pleased to provide all integrated cleaning services with the latest cleaning methods and equipment at the lowest costs through our mobile cars..
        /// </summary>
        internal static string AppHomeText {
            get {
                return ResourceManager.GetString("AppHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Care Application.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        internal static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Washing.
        /// </summary>
        internal static string ChemicalWashing {
            get {
                return ResourceManager.GetString("ChemicalWashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Washing the ceiling, doors, chairs, tables and menus with vacuuming the dust in the floor with a broom and washing the pedals - polishing for the tableau - freshener - paper pedals - cleaning the glass.
        ///• The possibility of chemical washing the bag for 50 pounds.
        ///• A chemical wash will add 60 pounds without dismantling chairs..
        /// </summary>
        internal static string ChemicalWashingDes {
            get {
                return ResourceManager.GetString("ChemicalWashingDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t remove.
        /// </summary>
        internal static string ClientMessage {
            get {
                return ResourceManager.GetString("ClientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string CT_X0001 {
            get {
                return ResourceManager.GetString("CT-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string CT_X0002 {
            get {
                return ResourceManager.GetString("CT-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code can not be empty.
        /// </summary>
        internal static string CT_X0003 {
            get {
                return ResourceManager.GetString("CT-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not found.
        /// </summary>
        internal static string CT_X0004 {
            get {
                return ResourceManager.GetString("CT-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating a Car type with empty values, please check your inputs..
        /// </summary>
        internal static string CT_X0005 {
            get {
                return ResourceManager.GetString("CT-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Car type with the same name is already exists.
        /// </summary>
        internal static string CT_X0006 {
            get {
                return ResourceManager.GetString("CT-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name can not be empty.
        /// </summary>
        internal static string CT_X0007 {
            get {
                return ResourceManager.GetString("CT-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name can not be empty.
        /// </summary>
        internal static string CT_X0008 {
            get {
                return ResourceManager.GetString("CT-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic description can not be empty.
        /// </summary>
        internal static string CT_X0009 {
            get {
                return ResourceManager.GetString("CT-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English description can not be empty.
        /// </summary>
        internal static string CT_X0010 {
            get {
                return ResourceManager.GetString("CT-X0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update a Car type with empty values, please check your inputs..
        /// </summary>
        internal static string CT_X0011 {
            get {
                return ResourceManager.GetString("CT-X0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price.
        /// </summary>
        internal static string DeliveryPrice {
            get {
                return ResourceManager.GetString("DeliveryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial Up.
        /// </summary>
        internal static string DialUp {
            get {
                return ResourceManager.GetString("DialUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Don&apos;t support away services, contact with the managment for more support.
        /// </summary>
        internal static string DistanceError {
            get {
                return ResourceManager.GetString("DistanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while commiting the order as done.
        /// </summary>
        internal static string DoneError {
            get {
                return ResourceManager.GetString("DoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string DY_X0001 {
            get {
                return ResourceManager.GetString("DY-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string DY_X0002 {
            get {
                return ResourceManager.GetString("DY-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string DY_X0003 {
            get {
                return ResourceManager.GetString("DY-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating a day with empty values, please check your inputs..
        /// </summary>
        internal static string DY_X0004 {
            get {
                return ResourceManager.GetString("DY-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic day name can not be empty.
        /// </summary>
        internal static string DY_X0005 {
            get {
                return ResourceManager.GetString("DY-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English day name can not be empty.
        /// </summary>
        internal static string DY_X0006 {
            get {
                return ResourceManager.GetString("DY-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day name with the same name is already exists.
        /// </summary>
        internal static string DY_X0007 {
            get {
                return ResourceManager.GetString("DY-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update a day with empty values, please check your inputs..
        /// </summary>
        internal static string DY_X0008 {
            get {
                return ResourceManager.GetString("DY-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day is not found.
        /// </summary>
        internal static string DY_X0009 {
            get {
                return ResourceManager.GetString("DY-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Washing.
        /// </summary>
        internal static string EngineWashing {
            get {
                return ResourceManager.GetString("EngineWashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor is washed with foam intended for cleaning oils and grease and microfiber towels only.
        /// </summary>
        internal static string EngineWashingDes {
            get {
                return ResourceManager.GetString("EngineWashingDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string EPS_X0001 {
            get {
                return ResourceManager.GetString("EPS-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string EPS_X0002 {
            get {
                return ResourceManager.GetString("EPS-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string EPS_X0003 {
            get {
                return ResourceManager.GetString("EPS-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra price setting is not found.
        /// </summary>
        internal static string EPS_X0004 {
            get {
                return ResourceManager.GetString("EPS-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating Extra price setting with empty values, please check your inputs..
        /// </summary>
        internal static string EPS_X0005 {
            get {
                return ResourceManager.GetString("EPS-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not selected.
        /// </summary>
        internal static string EPS_X0006 {
            get {
                return ResourceManager.GetString("EPS-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not selected.
        /// </summary>
        internal static string EPS_X0007 {
            get {
                return ResourceManager.GetString("EPS-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra price can not be equal or less than 0.
        /// </summary>
        internal static string EPS_X0008 {
            get {
                return ResourceManager.GetString("EPS-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update Extra price setting with empty values, please check your inputs..
        /// </summary>
        internal static string EPS_X0009 {
            get {
                return ResourceManager.GetString("EPS-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string EX_X0001 {
            get {
                return ResourceManager.GetString("EX-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating Expense with empty values, please check your inputs..
        /// </summary>
        internal static string EX_X0002 {
            get {
                return ResourceManager.GetString("EX-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can not be empty.
        /// </summary>
        internal static string EX_X0003 {
            get {
                return ResourceManager.GetString("EX-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash can not be equal or less than 0.
        /// </summary>
        internal static string EX_X0004 {
            get {
                return ResourceManager.GetString("EX-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Charge.
        /// </summary>
        internal static string ExtraCharge {
            get {
                return ResourceManager.GetString("ExtraCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name *.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full address *.
        /// </summary>
        internal static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        internal static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naivgate To.
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPS in your device.
        /// </summary>
        internal static string GPSDeciveError {
            get {
                return ResourceManager.GetString("GPSDeciveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device doesn&apos;t support GPS location detection!.
        /// </summary>
        internal static string GPSLocationError {
            get {
                return ResourceManager.GetString("GPSLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string HOW_X0001 {
            get {
                return ResourceManager.GetString("HOW-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour of work is not found.
        /// </summary>
        internal static string HOW_X0002 {
            get {
                return ResourceManager.GetString("HOW-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string HOW_X0003 {
            get {
                return ResourceManager.GetString("HOW-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string HOW_X0004 {
            get {
                return ResourceManager.GetString("HOW-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not provided.
        /// </summary>
        internal static string HOW_X0005 {
            get {
                return ResourceManager.GetString("HOW-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string HR_X0001 {
            get {
                return ResourceManager.GetString("HR-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour is not found.
        /// </summary>
        internal static string HR_X0002 {
            get {
                return ResourceManager.GetString("HR-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string HR_X0003 {
            get {
                return ResourceManager.GetString("HR-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string HR_X0004 {
            get {
                return ResourceManager.GetString("HR-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers Away.
        /// </summary>
        internal static string KilometersAway {
            get {
                return ResourceManager.GetString("KilometersAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.m.
        /// </summary>
        internal static string Km {
            get {
                return ResourceManager.GetString("Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unanle to get location!.
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable location permission in your App Settings.
        /// </summary>
        internal static string LocationPermissionError {
            get {
                return ResourceManager.GetString("LocationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s type *.
        /// </summary>
        internal static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or create a new account.
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make An Appointment.
        /// </summary>
        internal static string MakeAnAppointment {
            get {
                return ResourceManager.GetString("MakeAnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t place the order, please try again, if the issue still exists, contact with the managment.
        /// </summary>
        internal static string MakeOrderError {
            get {
                return ResourceManager.GetString("MakeOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person&apos;s Name *.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate To.
        /// </summary>
        internal static string NavigateTo {
            get {
                return ResourceManager.GetString("NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Addresses.
        /// </summary>
        internal static string NoAddresses {
            get {
                return ResourceManager.GetString("NoAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Orders.
        /// </summary>
        internal static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Washing.
        /// </summary>
        internal static string NormalWashing {
            get {
                return ResourceManager.GetString("NormalWashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust suction - tableau - menus - doors - chairs - floors - pedal washing - glass - tableware polish - freshener - paper pedals.
        /// </summary>
        internal static string NormalWashingDes {
            get {
                return ResourceManager.GetString("NormalWashingDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Placed.
        /// </summary>
        internal static string OrderPlaced {
            get {
                return ResourceManager.GetString("OrderPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry external wash.
        /// </summary>
        internal static string OutsideWashingNormal {
            get {
                return ResourceManager.GetString("OutsideWashingNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full exterior wash, rims cleaning and polishing + in addition to an outer layer of wax that gives protection and shine.
        /// </summary>
        internal static string OutsideWashingNormalDes {
            get {
                return ResourceManager.GetString("OutsideWashingNormalDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number *.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default App Language.
        /// </summary>
        internal static string PickLanguage {
            get {
                return ResourceManager.GetString("PickLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By.
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string RE_X0001 {
            get {
                return ResourceManager.GetString("RE-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating Revenue with empty values, please check your inputs..
        /// </summary>
        internal static string RE_X0002 {
            get {
                return ResourceManager.GetString("RE-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can not be empty.
        /// </summary>
        internal static string RE_X0003 {
            get {
                return ResourceManager.GetString("RE-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash can not be equal or less than 0.
        /// </summary>
        internal static string RE_X0004 {
            get {
                return ResourceManager.GetString("RE-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t remove the order, please try again.
        /// </summary>
        internal static string RemoveError {
            get {
                return ResourceManager.GetString("RemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Location.
        /// </summary>
        internal static string RequestLocation {
            get {
                return ResourceManager.GetString("RequestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RequestPersonName {
            get {
                return ResourceManager.GetString("RequestPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string RequestPhoneNumber {
            get {
                return ResourceManager.GetString("RequestPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Time.
        /// </summary>
        internal static string RequestTime {
            get {
                return ResourceManager.GetString("RequestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to have full impact for the selected language.
        /// </summary>
        internal static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string SE_X0001 {
            get {
                return ResourceManager.GetString("SE-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service can not be empty.
        /// </summary>
        internal static string SE_X0002 {
            get {
                return ResourceManager.GetString("SE-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string SE_X0003 {
            get {
                return ResourceManager.GetString("SE-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string SE_X0004 {
            get {
                return ResourceManager.GetString("SE-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not selected.
        /// </summary>
        internal static string SE_X0005 {
            get {
                return ResourceManager.GetString("SE-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not found.
        /// </summary>
        internal static string SE_X0006 {
            get {
                return ResourceManager.GetString("SE-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating a Service with empty values, please check your inputs..
        /// </summary>
        internal static string SE_X0007 {
            get {
                return ResourceManager.GetString("SE-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base price can not be less or equal to 0.
        /// </summary>
        internal static string SE_X0008 {
            get {
                return ResourceManager.GetString("SE-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name can not be empty .
        /// </summary>
        internal static string SE_X0009 {
            get {
                return ResourceManager.GetString("SE-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name can not be empty .
        /// </summary>
        internal static string SE_X0010 {
            get {
                return ResourceManager.GetString("SE-X0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with same name already exists .
        /// </summary>
        internal static string SE_X0011 {
            get {
                return ResourceManager.GetString("SE-X0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update a service with empty values, please check your inputs..
        /// </summary>
        internal static string SE_X0012 {
            get {
                return ResourceManager.GetString("SE-X0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic description can not be empty.
        /// </summary>
        internal static string SE_X0013 {
            get {
                return ResourceManager.GetString("SE-X0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English description can not be empty.
        /// </summary>
        internal static string SE_X0014 {
            get {
                return ResourceManager.GetString("SE-X0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name *.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Description.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string SET_X0001 {
            get {
                return ResourceManager.GetString("SET-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting is not found.
        /// </summary>
        internal static string SET_X0002 {
            get {
                return ResourceManager.GetString("SET-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string SET_X0003 {
            get {
                return ResourceManager.GetString("SET-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language can not be empty.
        /// </summary>
        internal static string SET_X0004 {
            get {
                return ResourceManager.GetString("SET-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating setting with empty values, please check your inputs..
        /// </summary>
        internal static string SET_X0005 {
            get {
                return ResourceManager.GetString("SET-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type is not selected.
        /// </summary>
        internal static string SET_X0006 {
            get {
                return ResourceManager.GetString("SET-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not selected.
        /// </summary>
        internal static string SET_X0007 {
            get {
                return ResourceManager.GetString("SET-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max kilometers can not be less or equal to 0.
        /// </summary>
        internal static string SET_X0008 {
            get {
                return ResourceManager.GetString("SET-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min kilometers can not be less or equal to 0.
        /// </summary>
        internal static string SET_X0009 {
            get {
                return ResourceManager.GetString("SET-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Kilometers can not be equal to Max Kilometers.
        /// </summary>
        internal static string SET_X0010 {
            get {
                return ResourceManager.GetString("SET-X0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min kilometers can not be greater than Max kilometers.
        /// </summary>
        internal static string SET_X0011 {
            get {
                return ResourceManager.GetString("SET-X0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers rate can not be less or equal to 0.
        /// </summary>
        internal static string SET_X0012 {
            get {
                return ResourceManager.GetString("SET-X0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, your selected address is out of our service scope for the selected service, please either change your address or try to pick another service.
        /// </summary>
        internal static string SET_X0013 {
            get {
                return ResourceManager.GetString("SET-X0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setting with the same service and cat type has been set before.
        /// </summary>
        internal static string SET_X0014 {
            get {
                return ResourceManager.GetString("SET-X0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered phone number or password are not correct.
        /// </summary>
        internal static string SigninError {
            get {
                return ResourceManager.GetString("SigninError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the entered data can&apos;t set up an account for you, please make sure you entered valida data or not duplicated.
        /// </summary>
        internal static string SignupError {
            get {
                return ResourceManager.GetString("SignupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key is not in the correct format .
        /// </summary>
        internal static string TR_X0001 {
            get {
                return ResourceManager.GetString("TR-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting is not found.
        /// </summary>
        internal static string TR_X0002 {
            get {
                return ResourceManager.GetString("TR-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string TR_X0003 {
            get {
                return ResourceManager.GetString("TR-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t creating transaction with empty values, please check your inputs..
        /// </summary>
        internal static string TR_X0004 {
            get {
                return ResourceManager.GetString("TR-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not provided.
        /// </summary>
        internal static string TR_X0005 {
            get {
                return ResourceManager.GetString("TR-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type is not provided .
        /// </summary>
        internal static string TR_X0006 {
            get {
                return ResourceManager.GetString("TR-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work hour is not provided.
        /// </summary>
        internal static string TR_X0007 {
            get {
                return ResourceManager.GetString("TR-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not found.
        /// </summary>
        internal static string TR_X0008 {
            get {
                return ResourceManager.GetString("TR-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not sign in with empty values.
        /// </summary>
        internal static string UR_X0001 {
            get {
                return ResourceManager.GetString("UR-X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be empty .
        /// </summary>
        internal static string UR_X0002 {
            get {
                return ResourceManager.GetString("UR-X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number can not be empty.
        /// </summary>
        internal static string UR_X0003 {
            get {
                return ResourceManager.GetString("UR-X0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number or Password is not correct , Register for a new account or try to sign in again.
        /// </summary>
        internal static string UR_X0004 {
            get {
                return ResourceManager.GetString("UR-X0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing the request, please try again later!.
        /// </summary>
        internal static string UR_X0005 {
            get {
                return ResourceManager.GetString("UR-X0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can not be empty .
        /// </summary>
        internal static string UR_X0006 {
            get {
                return ResourceManager.GetString("UR-X0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name can not be empty .
        /// </summary>
        internal static string UR_X0007 {
            get {
                return ResourceManager.GetString("UR-X0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is already exists , try to sign in instead.
        /// </summary>
        internal static string UR_X0008 {
            get {
                return ResourceManager.GetString("UR-X0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not sign up with empty values .
        /// </summary>
        internal static string UR_X0009 {
            get {
                return ResourceManager.GetString("UR-X0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be empty.
        /// </summary>
        internal static string UR_X0010 {
            get {
                return ResourceManager.GetString("UR-X0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        internal static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
    }
}
